<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <SignAssembly>True</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\Src\AwesomeAssertions\AwesomeAssertions.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Src\AwesomeAssertions\AwesomeAssertions.csproj" />
    </ItemGroup>

</Project>
